### ISSUE TITLE
请问怎么运行api呢

### ISSUE THREAD

**Issue by coderfeiwu** [coder-hxl/airbnb-api#1]
怎么运行api呢

**Comment by coder-hxl** [comment]
1. 安装依赖
2. 在 MySQL 创建一个名为 airbnb 的数据库，然后将 database/airbnb.sql 文件导入进去
3. 然后修改 .env 文件
4. 最后运行 
 ```shell
  pnpm start
```
项目就启动了

**Comment by coder-hxl** [comment]
前端: https://github.com/coder-hxl/airbnb
