### ISSUE TITLE
图片资源访问问题

### ISSUE THREAD

**Issue by abs612** [coder-hxl/airbnb-api#2]
数据库里的图片地址我改为了自己的域名和端口号，无法访问？
https://[airbnb.sjnh.me:8691/api/room/193581217](https://airbnb.sjnh.me:8691/api/room/193581217)
图片无法访问？怎么解决？求大佬解答
![image](https://github.com/coder-hxl/airbnb-api/assets/144533817/e75e3898-9099-428a-98e0-e49404f60d2e)
https://airbnb.sjnh.me:8691
代理到
http://35.230.125.144:8690

**Comment by abs612** [comment]
![image](https://github.com/coder-hxl/airbnb-api/assets/144533817/7dc08bb6-2a46-4065-badd-60658d2942e5)
upload文件有数据

**Comment by coder-hxl** [comment]
能正常使用 GitHub 图床吗
试试 `USE_GITHUB_REP=true`

**Comment by abs612** [comment]
> 能正常使用 GitHub 图床吗 试试 `USE_GITHUB_REP=true`

确实可以正常访问了。
是我配置的不正确，导致无法访问到图片吗？github有时候打不开，图片加载慢。
还是希望可以机器本地访问

不过还是谢谢大佬的后端服务
